[package]
description = "An incredibly jank tool to update cron jobs over ssh"
edition = "2021"
name = "ssh-cron"
version = "0.1.0"

[dependencies]
async-ssh2-tokio = "0.6.7"
indicatif = "0.17.5"
inquire = "0.6.2"
tokio = "1"
