name: CD
on:
  push:

env:
  RELEASE_BIN: ssh-cron

jobs:
  build_release:
    name: Build release
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Create artifact directory
        run: mkdir artifacts

      - name: Create Windows archive
        run: 7z a -tzip ./artifacts/${{ env.RELEASE_BIN }}-windows-x86_64.zip ./target/release/${{ env.RELEASE_BIN }}.exe
        if: matrix.os == 'windows-latest'

      - name: Upload Windows archive
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.RELEASE_BIN }}-windows-x86_64.zip
          path: ./artifacts/${{ env.RELEASE_BIN }}-windows-x86_64.zip
        if: matrix.os == 'windows-latest'

      - name: Create macOS archive
        run: tar -czvf ./artifacts/${{ env.RELEASE_BIN }}-mac-x86_64.tar.gz ./target/release/${{ env.RELEASE_BIN }}
        if: matrix.os == 'macos-latest'

      - name: Upload macOS archive
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.RELEASE_BIN }}-mac-x86_64.tar.gz
          path: ./artifacts/${{ env.RELEASE_BIN }}-mac-x86_64.tar.gz
        if: matrix.os == 'macos-latest'
